var colors = {
	yellow: 'rgb(247,160,31)',
	orange: 'rgb(230,97,45)',
	pink: 'rgb(197,61,75)',
	red: 'rgb(184,49,42)',
	darkred: 'rgb(141,37,33)',
	brown: 'rgb(109,32,33)',
	purple: 'rgb(83,30,76)',
	darkpurple: 'rgb(58,26,58)',
};

var sections = [{
	'size': 30,
	'text': "+50",
	'value': 50,
	'color': colors.purple
}, {
	'size': 20,
	'text': "LADOO",
	'value': undefined,
	'color': colors.darkpurple
}, {
	'size': 20,
	'text': "+1 TURN",
	'value': "t1",
	'color': colors.yellow
}, {
	'size': 20,
	'text': "HALF POINTS",
	'value': "ph",
	'color': colors.orange
}, {
	'size': 20,
	'text': "-10",
	'value': -10,
	'color': colors.pink
}, {
	'size': 20,
	'text': "+10",
	'value': 10,
	'color': colors.red
}, {
	'size': 20,
	'text': "POINTS=0",
	'value': "p0",
	'color': colors.darkred
}, {
	'size': 30,
	'text': "-101",
	'value': -101,
	'color': colors.brown
}, {
	'size': 30,
	'text': "+101",
	'value': 101,
	'color': colors.purple,
}, {
	'size': 20,
	'text': "LADOO",
	'value': undefined,
	'color': colors.darkpurple,
}, {
	'size': 20,
	'text': "+500",
	'value': 500,
	'color': colors.yellow,
}, {
	'size': 20,
	'text': "+15",
	'value': 15,
	'color': colors.orange,
}, {
	'size': 20,
	'text': "-15",
	'value': -15,
	'color': colors.pink,
}, {
	'size': 20,
	'text': "-24",
	'value': -24,
	'color': colors.red,
}, {
	'size': 20,
	'text': "+24",
	'value': 24,
	'color': colors.darkred,
}, {
	'size': 30,
	'text': "-50",
	'value': -50,
	'color': colors.brown
}];